import turtle as trtl

painter = trtl.Turtle()

#Makes the main House
painter.fillcolor('blue')
painter.begin_fill()
painter.pencolor('blue')
painter.right(90)
painter.goto(100,0)
painter.goto(100,200)
painter.goto(0,200)
painter.goto(0,0)
painter.penup
#Makes the roof
painter.goto(0,200)
painter.end_fill()
painter.pendown
painter.fillcolor('black')
painter.pencolor('black')
painter.begin_fill()
painter.goto(50,350)
painter.goto(100,200)
painter.end_fill()
painter.penup()
#Makes the Tree Base
painter.goto(-100,0)
painter.pendown()
painter.begin_fill()
painter.goto(-120,0)
painter.goto(-120,50)
painter.goto(-100,50)
painter.goto(-100,0)
painter.end_fill()
painter.penup()
#Makes the tree Triangle, leaves.
painter.goto(-50,50)
painter.pencolor('green')
painter.pendown()
painter.fillcolor('green')
painter.begin_fill()
painter.goto(-170,50)
painter.goto(-110,300)
painter.goto(-50,50)
painter.end_fill()
painter.penup()
#Makes White Door
painter.pencolor('blue')
painter.fillcolor('white')
painter.goto(40,0)
painter.pendown()
painter.begin_fill()
painter.goto(40,25)
painter.goto(60,25)
painter.goto(60,0)
painter.end_fill()
painter.penup()
#Makes white window.
painter.goto(60,150)
painter.left(180)
painter.fillcolor('white')
painter.begin_fill()
painter.circle(10)
painter.end_fill()
painter.penup()
#Makes Red window.
painter.goto(75,230)
painter.pendown()
painter.pencolor('red')
painter.begin_fill()
painter.circle(25)
painter.end_fill()

window = trtl.Screen()
window.mainloop()